Comment out new-project in grafana addon
minishift/minishift-addons pull request #143
Opened 2018-07-26 18:25 UTC by cunningt

Comment out new-project in grafana addon - grafana is often paired with Prometheus, but the new-project in the grafana addon hinders that.   Once conditionals are added, probably should test for whether the project namespace exists or not.

2018-08-24 18:37 UTC, praveenkumar requested changes

2018-08-24 18:37 UTC, praveenkumar commented on add-ons/grafana/grafana.addon
> +#oc adm new-project #{namespace}
`#` comment out this step but if you want to run it but ignore the failure then better to use `!`

2018-08-24 18:38 UTC, praveenkumar commented on add-ons/grafana/grafana.addon
> +#oc adm new-project #{namespace}
@cunningt Also now `oc new-project` works without any issue.

2018-08-25 02:33 UTC, brgnepal requested changes
Hi @cunningt ,

I am not sure the reason to comment out `oc adm `.. particular line

I am having difficulty when applying addon when the line is commted.
```
$ minishift addons install grafana
Addon 'grafana' installed

$ minishift addons apply grafana --addon-env namespace="grafana-proj"
-- Applying addon 'grafana':.error: error processing template "grafana-proj/hawkular-grafana-persistent": namespaces "grafana-proj" not found
Error applying the add-on: Error executing command 'oc new-app -f openshift-template-persistent.yml -n #{namespace}'.

# Uncommented it
$ vim ~/.minishift/addons/grafana/grafana.addon 

$ minishift addons apply grafana --addon-env namespace="grafana-proj"
-- Applying addon 'grafana':..
You have installed grafana
To access grafana go to http://hawkular-grafana-grafana-proj.192.168.42.34.nip.io
See http://www.hawkular.org/blog/2016/10/24/hawkular-metrics-openshift-and-grafana.html
To get a permanent credential token, if management-infra addons is installed, use "oc sa get-token management-admin -n management-infra --as=system:admin"

To delete:
    oc delete project -n grafana-proj --as=system:admin
```

2018-08-25 15:28 UTC, cunningt commented
@budhram @praveenkumar The problem here is that oc new-project returns non zero when the project already exists ...

```
tcunning@tcunning-OSX:/tmp/prometheus-operator$ oc new-project myproject
Error from server (AlreadyExists): project.project.openshift.io "myproject" already exists
tcunning@tcunning-OSX:/tmp/prometheus-operator$ echo $?
1
```

so the script bombs out at that point if the project doesn't exist.     You can easily do a oc new-project and create a project, but the inclusion of the oc new-project line here means you can't ever install grafana into a previously existing namespace - which means the addon is essentially useless because the main use case for grafana is going to be installing it into a namespace with other stuff.

The most common use case for grafana I think is going to be install it into a previously existing namespace that has some sort of data to be graphed (a database, prometheus, etc)

It'd be great if oc new-project had a flag like --no-fail that returned 0 if the project exists.

2024-03-18 11:25 UTC, closed without merging