fabric8-launcher: make Launcher Booster Catalog customizable
minishift/minishift-addons pull request #148
Opened 2018-08-11 15:10 UTC by vorburger

2018-08-14 07:00 UTC, praveenkumar commented
@vorburger Can someone from your team or you test this change because we are not so expert about what to test here and how it should behave.

2018-08-14 10:51 UTC, vorburger commented
@praveenkumar I'll test it, but do you have any idea / know anyone who could help re. a better way to avoid the default values for the ..REPOSITORY and ..REF from the original launcher-template.yaml here?

2018-08-21 09:16 UTC, praveenkumar commented
@vorburger I am not sure, might be good to ask on launcher github issue tracker?

2018-08-21 10:34 UTC, vorburger commented
@praveenkumar but it isn't really a Launcher specific issue... this is more of a minishift-addon thing: So I want users to have the option to override those two things, but they are options which already have default values, in the YAML template. So if a user does not specify those 2 options, those should be used. But I have copy/pasted those from the YAML template into the minishift addon, and in an ideal world that should be avoided I guess. Do you see what I mean?

2018-08-21 12:39 UTC, praveenkumar commented
@vorburger let me know if I understand correctly, as of now you put those value as part of `Default-Vars` but you also want this value can be over ride by user then also put those variable as part of `Required-Vars` so that user can override using like below.

```
$ minishift addon apply -a "LAUNCHER_BOOSTER_CATALOG_REPOSITORY=foo.com" -a "LAUNCHER_BOOSTER_CATALOG_REF=bar"
```

2018-08-21 12:40 UTC, praveenkumar requested changes

2018-08-21 12:40 UTC, praveenkumar commented on add-ons/fabric8-launcher/fabric8-launcher.addon
> +# Var-Defaults: OPENSHIFT_USERNAME=developer,OPENSHIFT_PASSWORD=developer,CONSOLE_URL=https://#{ip}:8443,LAUNCHER_PROJ=rhoarpad,LAUNCHERLAUNCHER_BOOSTER_CATALOG_REPOSITORY=https://github.com/fabric8-
Typo `LAUNCHERLAUNCHER_BOOSTER_CATALOG_REPOSITORY` should be `LAUNCHER_BOOSTER_CATALOG_REPOSITORY`

2018-08-21 12:40 UTC, praveenkumar commented on add-ons/fabric8-launcher/fabric8-launcher.addon
> +oc new-app fabric8-launcher --name=launcher -n #{LAUNCHER_PROJ} -p LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME=#{GITHUB_USERNAME} -p LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN=#{GITHUB_TOKEN} -p LAUNCHER_MISSI
ditto here.

2021-12-04 10:00 UTC, vorburger commented
Hello @praveenkumar I'm doing a year end clean up of my personal https://github.com/pulls and wanted to ask if you would still consider merging this very old Pull Request if I rebased it, or if we should forget about and close this? (This is a bulk message I'm posting to many issues to gauge what is still revelant.)

2021-12-05 10:37 UTC, gbraad commented
We do not support minishift anymore. The tool was made EOL at the end of
August.

No member of the team has time to spend on testing or rebasing. If you do
this, perhaps it can be merged.

On Sat, Dec 4, 2021, 18:00 Michael Vorburger ⛑️ ***@***.***>
wrote:

> Hello @praveenkumar <https://github.com/praveenkumar> I'm doing a year
> end clean up of my personal https://github.com/pulls and wanted to ask if
> you would still consider merging this very old Pull Request if I rebased
> it, or if we should forget about and close this? (This is a bulk message
> I'm posting to many issues to gauge what is still revelant.)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/minishift/minishift-addons/pull/148#issuecomment-986001943>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAAOZXXJOOR4QJIYTYACV3UPHRFRANCNFSM4FPEZSAQ>
> .
>

2021-12-05 10:41 UTC, closed without merging